### ISSUE TITLE
develop `get_ci_data()` function

### ISSUE THREAD

**Issue by jmlondon** [jmlondon/cookinlet-seal-movt#2]

**Comment by jmlondon** [comment]
added @StacieKozHardy so she can confirm my SQL queries are referencing appropriate sources

see SQL queries at https://github.com/jmlondon/cookinlet-seal-movt/blob/1d032579fbf864e84d54685868aa52c935d72c97/R/get_ci_data.R#L20 and at https://github.com/jmlondon/cookinlet-seal-movt/blob/1d032579fbf864e84d54685868aa52c935d72c97/R/get_ci_data.R#L40

**Comment by staciekoslovsky-noaa** [comment]
I double-checked the queries (they look great) and did some QA of the data. There are 91 seals tagged as part of this project. The 1st query returns 89 deployids; the 2 missing deployids (PV2004_0215_03T0079,  PV2006_0283_05L0076) have a matching deploy_dt and end_dt, so no expected data for them. All good there. The 2nd query returns 82 deployids.  In addition to the 2 missing from the first query, there are an additional 7 deployids from 2005 (PV2005_0236_03T0161, PV2005_0238_03T0155, PV2005_0239_03T0153, PV2005_0241_03T0162, PV2005_0245_03T0166, PV2005_0248_03T0172, PV2005_0249_03T0154) that do not have any data being returned in the query. I dhouble-checked the data in telem.tbl_wc_histos_timeline_qa, and none of those deployids have data within the table, so I think just no data for these.

**Comment by jmlondon** [comment]
Thank you @StacieKozHardy for doing those checks.

I'll close this issue keep the project moving forward
